# Generated by Django 5.1.6 on 2025-03-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_rename_video_file_video_original_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('cats', 'Cats'), ('cities', 'Cities'), ('nature', 'Nature')], default='cats', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(upload_to='thumbnails/'),
        ),
    ]
